#include<stdio.h>
#include<conio.h>
int main()
{
 int a=10,b=30,f=30,c,d,e,g,h,i;
 c=a<b;
 d=b<=a;
 e=a>b;
 g=b<=f;
 h=b==f;
 i=a!=b;


 printf(" this is the value of c %d\n ",c);
  printf(" this is the value of d %d\n ",d);
  printf(" this is the value of e %d\n ",e);
   printf(" this is the value of g %d\n ",g);
  printf(" this is the value of h %d\n ",h);
  printf(" this is the value of i %d\n ",i);
 getch();

}
